<a href="https://colab.research.google.com/github/OmkarBhosale06/LC50_ML/blob/main/LC50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [6]:
dataset = '/content/qsar_fish_toxicity.csv'
data = pd.read_csv(dataset)

      
  
  



In [7]:

data.head()

CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP  LC50 [-LOG(mol/L)]
0  3.260      0.829   1.676      0      1  1.453               3.770
1  2.189      0.580   0.863      0      0  1.348               3.115
2  2.125      0.638   0.831      0      0  1.348               3.531
3  3.027      0.331   1.472      1      0  1.807               3.510
4  2.094      0.827   0.860      0      0  1.886               5.390

In [8]:
data.tail()

CIC0  SM1_Dz(Z)  GATS1i  NdsCH  NdssC  MLOGP  LC50 [-LOG(mol/L)]
903  2.801      0.728   2.226      0      2  0.736               3.109
904  3.652      0.872   0.867      2      3  3.983               4.040
905  3.763      0.916   0.878      0      6  2.918               4.818
906  2.831      1.393   1.077      0      1  0.906               5.317
907  4.057      1.032   1.183      1      3  4.754               8.201

In [9]:
data.isnull().sum()

CIC0                  0
SM1_Dz(Z)             0
GATS1i                0
NdsCH                 0
NdssC                 0
MLOGP                 0
LC50 [-LOG(mol/L)]    0
dtype: int64

In [10]:
data.describe()

CIC0   SM1_Dz(Z)  ...       MLOGP  LC50 [-LOG(mol/L)]
count  908.000000  908.000000  ...  908.000000          908.000000
mean     2.898129    0.628468  ...    2.109285            4.064431
std      0.756088    0.428459  ...    1.433181            1.455698
min      0.667000    0.000000  ...   -2.884000            0.053000
25%      2.347000    0.223000  ...    1.209000            3.151750
50%      2.934000    0.570000  ...    2.127000            3.987500
75%      3.407000    0.892750  ...    3.105000            4.907500
max      5.926000    2.171000  ...    6.515000            9.612000

[8 rows x 7 columns]

In [11]:
data.std()

CIC0                  0.756088
SM1_Dz(Z)             0.428459
GATS1i                0.394303
NdsCH                 0.605335
NdssC                 0.861279
MLOGP                 1.433181
LC50 [-LOG(mol/L)]    1.455698
dtype: float64

In [35]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(data)

array([[ 0.47887329,  0.46828848,  0.97036948, ...,  0.59748428,
        -0.45817453, -0.20237219],
       [-0.93840825, -0.11318414, -1.09263435, ..., -0.56421963,
        -0.53147852, -0.652576  ],
       [-1.02310108,  0.02225928, -1.173835  , ..., -0.56421963,
        -0.53147852, -0.36664503],
       ...,
       [ 1.14450599,  0.67145361, -1.05457155, ...,  6.40600388,
         0.56459064,  0.5179539 ],
       [-0.08883332,  1.78535897, -0.54960505, ...,  0.59748428,
        -0.8400534 ,  0.86093359],
       [ 1.53356366,  0.94234045, -0.28062792, ...,  2.92089212,
         1.84636323,  2.84320501]])

In [41]:
X = data.iloc[:,:-1].values
Y = data.iloc[:,-1].values
print(X)


[[3.26  0.829 1.676 0.    1.    1.453]
 [2.189 0.58  0.863 0.    0.    1.348]
 [2.125 0.638 0.831 0.    0.    1.348]
 ...
 [3.763 0.916 0.878 0.    6.    2.918]
 [2.831 1.393 1.077 0.    1.    0.906]
 [4.057 1.032 1.183 1.    3.    4.754]]


In [42]:
print(Y)

[3.77  3.115 3.531 3.51  5.39  1.819 3.947 3.513 4.402 3.021 3.21  2.371
 3.919 3.03  2.736 2.157 2.413 0.898 0.45  3.733 2.976 6.535 5.643 4.629
 4.838 4.081 3.436 3.45  1.102 4.257 5.386 3.393 1.308 3.554 2.269 4.165
 5.896 4.829 4.59  2.092 3.665 3.56  4.805 3.174 7.899 2.67  4.016 3.857
 5.522 4.851 3.84  4.586 5.284 3.559 4.091 4.33  3.755 4.552 3.62  4.459
 2.827 6.38  4.786 3.861 3.262 6.297 3.546 2.92  3.203 2.283 1.559 3.47
 4.748 2.576 5.259 4.564 4.37  0.053 2.381 2.891 1.088 3.721 3.701 6.083
 4.628 3.7   1.842 3.396 2.99  3.573 2.271 2.085 3.822 3.29  3.84  3.979
 3.47  3.314 4.031 4.74  4.194 3.447 2.364 3.645 2.07  2.27  3.513 2.811
 2.832 1.639 2.016 1.651 4.097 3.123 3.231 5.052 3.572 2.436 2.567 1.795
 5.072 2.156 1.037 1.932 2.505 1.524 3.048 5.115 2.856 4.366 4.976 2.94
 4.538 3.391 2.692 3.825 3.206 1.78  0.533 3.299 2.914 1.18  3.168 3.446
 3.496 4.68  3.252 2.98  3.936 5.47  1.842 0.15  3.736 3.719 1.749 3.507
 3.979 5.363 4.396 3.984 1.02  2.973 3.182 5.055 4.82

In [43]:
regressor = LinearRegression()
X_train,Y_train,X_test,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [44]:
regressor.fit(X_train,Y_train)

ValueError: ignored